# Generated by Django 3.0.3 on 2020-02-11 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200210_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('primeiroNome', models.CharField(max_length=50)),
                ('ultimoNome', models.CharField(max_length=50)),
                ('endereco', models.TextField()),
                ('nomeUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precoTotal', models.FloatField()),
                ('quantItens', models.IntegerField(default=0)),
                ('pago', models.BooleanField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Usuario')),
            ],
        ),
    ]
