# Generated by Django 3.0.3 on 2020-02-20 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20200211_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Produto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
